# Generated by Django 6.1.1 on 2026-09-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='contact_method',
            field=models.CharField(choices=[('phone', 'Phone call'), ('email', 'Email')], default='phone', max_length=20),
        ),
    ]
