# Generated by Django 6.1.1 on 2026-09-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_bookingrequest_contact_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='contact_method',
            field=models.CharField(choices=[('phone', 'Phone call'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], default='phone', max_length=20),
        ),
    ]
